Repository AdnanHodzic/auto-cpufreq, pull requests merged in 2023-10, with the labels that each got.

#572 nix: replace local derivation with nixpkgs derivation
  flake.lock
  nix/default.nix
  nix/pkgs/setuptools-git-versioning.nix
Labels: hacktoberfest, hacktoberfest-accepted

#576 feat: support for pyproject.toml
  auto-cpufreq-installer
  auto_cpufreq/bin/__init__.py
  auto_cpufreq/bin/auto_cpufreq.py
  auto_cpufreq/bin/auto_cpufreq_gtk.py
  auto_cpufreq/core.py
  nix/default.nix
  poetry.lock
  pyproject.toml
  scripts/start_app
  setup.old.py
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#582 refactor(flake): improve usage
  flake.nix
  nix/default.nix
  nix/module.nix
  nix/shell.nix
Labels: hacktoberfest, hacktoberfest-accepted

#581 chore(auto-cpufreq-installer): removed dependence on record files for removal
  README.md
  auto-cpufreq-installer
  requirements.txt
  setup.old.py
Labels: hacktoberfest, hacktoberfest-accepted

#580 feat(cli): added supported for shell completions
  README.md
  auto_cpufreq/bin/auto_cpufreq.py
  scripts/auto-cpufreq-venv-wrapper
Labels: hacktoberfest, hacktoberfest-accepted

#587 Feature: Allow GUI to detect available update and install it
  auto_cpufreq/bin/auto_cpufreq.py
  auto_cpufreq/bin/auto_cpufreq_gtk.py
  auto_cpufreq/core.py
  auto_cpufreq/gui/app.py
  auto_cpufreq/gui/objects.py
Labels: enhancement, hacktoberfest

#584 Fix img link and adjust text
  README.md
Labels: hacktoberfest, hacktoberfest-accepted
